import type { GuestbookEntry } from "./types";

export const MOCK_GUESTBOOK_DATA: GuestbookEntry[] = [
  {
    id: 1,
    authorId: 101,
    authorName: "devKim",
    avatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
    content: "오늘도 모각코 파이팅! 다들 화이팅하세요 💪",
    createdAt: "2026-02-27T14:30:00Z",
  },
  {
    id: 2,
    authorId: 102,
    authorName: "codeLee",
    avatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
    content: "이 서비스 너무 좋아요. 집중 시간 관리가 편해졌어요.",
    createdAt: "2026-02-27T13:15:00Z",
  },
  {
    id: 3,
    authorId: 103,
    authorName: "hackPark",
    avatarUrl: "https://avatars.githubusercontent.com/u/3?v=4",
    content: "같이 코딩하니까 확실히 동기부여가 됩니다!",
    createdAt: "2026-02-27T12:00:00Z",
  },
  {
    id: 4,
    authorId: 104,
    authorName: "jsChoi",
    avatarUrl: "https://avatars.githubusercontent.com/u/4?v=4",
    content: "오늘 3시간 집중 성공! 내일은 4시간 도전해봐야겠다.",
    createdAt: "2026-02-27T11:45:00Z",
  },
  {
    id: 5,
    authorId: 105,
    authorName: "reactHan",
    avatarUrl: "https://avatars.githubusercontent.com/u/5?v=4",
    content: "방명록 기능 생겼네요! 좋습니다 👍",
    createdAt: "2026-02-27T10:30:00Z",
  },
  {
    id: 6,
    authorId: 106,
    authorName: "nodeJung",
    avatarUrl: "https://avatars.githubusercontent.com/u/6?v=4",
    content: "주말에도 모각코 하시는 분들 대단해요.",
    createdAt: "2026-02-26T22:00:00Z",
  },
  {
    id: 7,
    authorId: 107,
    authorName: "pyYoon",
    avatarUrl: "https://avatars.githubusercontent.com/u/7?v=4",
    content: "펫 시스템이 너무 귀여워요! 고퍼 키우는 중입니다.",
    createdAt: "2026-02-26T20:15:00Z",
  },
  {
    id: 8,
    authorId: 108,
    authorName: "goShin",
    avatarUrl: "https://avatars.githubusercontent.com/u/8?v=4",
    content: "리더보드 1등 찍어보고 싶다... 열심히 해야지.",
    createdAt: "2026-02-26T18:30:00Z",
  },
  {
    id: 9,
    authorId: 109,
    authorName: "rustKang",
    avatarUrl: "https://avatars.githubusercontent.com/u/9?v=4",
    content: "집중 모드 BGM이 좋아요. 코딩할 맛 납니다.",
    createdAt: "2026-02-26T16:00:00Z",
  },
  {
    id: 10,
    authorId: 110,
    authorName: "tsLim",
    avatarUrl: "https://avatars.githubusercontent.com/u/10?v=4",
    content: "TypeScript 프로젝트 진행 중인데, 여기서 집중하니까 잘 되네요.",
    createdAt: "2026-02-26T14:45:00Z",
  },
  {
    id: 11,
    authorId: 111,
    authorName: "vueOh",
    avatarUrl: "https://avatars.githubusercontent.com/u/11?v=4",
    content: "첫 방문입니다! 앞으로 자주 올게요.",
    createdAt: "2026-02-26T13:20:00Z",
  },
  {
    id: 12,
    authorId: 112,
    authorName: "swiftSeo",
    avatarUrl: "https://avatars.githubusercontent.com/u/12?v=4",
    content: "iOS 개발자인데 여기서 모각코 하니까 좋네요.",
    createdAt: "2026-02-26T12:00:00Z",
  },
  {
    id: 13,
    authorId: 113,
    authorName: "kotlinBae",
    avatarUrl: "https://avatars.githubusercontent.com/u/13?v=4",
    content: "채널별로 나뉘어져 있어서 소규모로 집중하기 좋아요.",
    createdAt: "2026-02-26T10:30:00Z",
  },
  {
    id: 14,
    authorId: 114,
    authorName: "cppNam",
    avatarUrl: "https://avatars.githubusercontent.com/u/14?v=4",
    content: "알고리즘 문제 풀 때 여기서 타이머 돌리면서 하면 효과적!",
    createdAt: "2026-02-25T23:00:00Z",
  },
  {
    id: 15,
    authorId: 115,
    authorName: "javaMin",
    avatarUrl: "https://avatars.githubusercontent.com/u/15?v=4",
    content: "스프링 부트 프로젝트 마감 다가오는데 여기서 힘 얻고 갑니다.",
    createdAt: "2026-02-25T21:30:00Z",
  },
  {
    id: 16,
    authorId: 116,
    authorName: "dartWon",
    avatarUrl: "https://avatars.githubusercontent.com/u/16?v=4",
    content: "Flutter 앱 개발 중! 다들 응원합니다 🎉",
    createdAt: "2026-02-25T19:00:00Z",
  },
  {
    id: 17,
    authorId: 117,
    authorName: "rubyHong",
    avatarUrl: "https://avatars.githubusercontent.com/u/17?v=4",
    content: "오픈소스 기여 준비 중인데, 모각코하면서 하니까 동기부여 됩니다.",
    createdAt: "2026-02-25T17:15:00Z",
  },
  {
    id: 18,
    authorId: 118,
    authorName: "phpJo",
    avatarUrl: "https://avatars.githubusercontent.com/u/18?v=4",
    content: "레거시 코드 리팩토링 중... 힘들지만 화이팅!",
    createdAt: "2026-02-25T15:30:00Z",
  },
  {
    id: 19,
    authorId: 119,
    authorName: "sqlYoo",
    avatarUrl: "https://avatars.githubusercontent.com/u/19?v=4",
    content: "DB 최적화 작업하다가 방명록 발견! 좋은 기능이네요.",
    createdAt: "2026-02-25T13:00:00Z",
  },
  {
    id: 20,
    authorId: 120,
    authorName: "dockerSon",
    avatarUrl: "https://avatars.githubusercontent.com/u/20?v=4",
    content: "컨테이너 오케스트레이션 공부 중입니다. 같이 공부해요!",
    createdAt: "2026-02-25T11:45:00Z",
  },
  {
    id: 21,
    authorId: 121,
    authorName: "k8sAhn",
    avatarUrl: "https://avatars.githubusercontent.com/u/21?v=4",
    content: "쿠버네티스 CKA 시험 준비 중! 다들 자격증 준비하시는 분?",
    createdAt: "2026-02-25T10:00:00Z",
  },
  {
    id: 22,
    authorId: 122,
    authorName: "awsKim2",
    avatarUrl: "https://avatars.githubusercontent.com/u/22?v=4",
    content: "클라우드 인프라 구축하면서 모각코! 생산성 최고.",
    createdAt: "2026-02-24T22:30:00Z",
  },
  {
    id: 23,
    authorId: 123,
    authorName: "mlPark",
    avatarUrl: "https://avatars.githubusercontent.com/u/23?v=4",
    content: "머신러닝 모델 학습시키면서 기다리는 동안 여기 옵니다 😄",
    createdAt: "2026-02-24T20:00:00Z",
  },
  {
    id: 24,
    authorId: 124,
    authorName: "dataLee2",
    avatarUrl: "https://avatars.githubusercontent.com/u/24?v=4",
    content: "데이터 파이프라인 구축 프로젝트 진행 중입니다.",
    createdAt: "2026-02-24T18:15:00Z",
  },
  {
    id: 25,
    authorId: 125,
    authorName: "devOpsChoi",
    avatarUrl: "https://avatars.githubusercontent.com/u/25?v=4",
    content: "CI/CD 파이프라인 개선 작업 완료! 오늘 하루 뿌듯합니다.",
    createdAt: "2026-02-24T16:30:00Z",
  },
  {
    id: 26,
    authorId: 126,
    authorName: "frontHan",
    avatarUrl: "https://avatars.githubusercontent.com/u/26?v=4",
    content: "CSS 애니메이션 작업 중인데, 픽셀 아트 스타일 참고하고 있어요!",
    createdAt: "2026-02-24T14:00:00Z",
  },
  {
    id: 27,
    authorId: 127,
    authorName: "backJung",
    avatarUrl: "https://avatars.githubusercontent.com/u/27?v=4",
    content: "API 설계하다가 쉬러 왔습니다. 잠깐 휴식!",
    createdAt: "2026-02-24T12:30:00Z",
  },
  {
    id: 28,
    authorId: 128,
    authorName: "fullYoon",
    avatarUrl: "https://avatars.githubusercontent.com/u/28?v=4",
    content: "풀스택 개발 공부 중! 프론트도 백도 다 재미있어요.",
    createdAt: "2026-02-24T10:00:00Z",
  },
  {
    id: 29,
    authorId: 129,
    authorName: "gameShin",
    avatarUrl: "https://avatars.githubusercontent.com/u/29?v=4",
    content: "게임 개발자인데 이 서비스 UI가 픽셀 아트라 친근해요!",
    createdAt: "2026-02-23T22:00:00Z",
  },
  {
    id: 30,
    authorId: 130,
    authorName: "secKang",
    avatarUrl: "https://avatars.githubusercontent.com/u/30?v=4",
    content: "보안 공부하면서 모각코! CTF 준비하시는 분 계신가요?",
    createdAt: "2026-02-23T20:30:00Z",
  },
  {
    id: 31,
    authorId: 101,
    authorName: "devKim",
    avatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
    content: "어제보다 30분 더 집중했어요. 점점 늘어나는 중!",
    createdAt: "2026-02-23T18:00:00Z",
  },
  {
    id: 32,
    authorId: 102,
    authorName: "codeLee",
    avatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
    content: "코드 리뷰 받으면서 많이 배우고 있습니다.",
    createdAt: "2026-02-23T16:15:00Z",
  },
  {
    id: 33,
    authorId: 103,
    authorName: "hackPark",
    avatarUrl: "https://avatars.githubusercontent.com/u/3?v=4",
    content: "해커톤 준비하면서 여기서 팀원들이랑 같이 코딩 중!",
    createdAt: "2026-02-23T14:30:00Z",
  },
  {
    id: 34,
    authorId: 104,
    authorName: "jsChoi",
    avatarUrl: "https://avatars.githubusercontent.com/u/4?v=4",
    content: "JavaScript 새 기능 공부하다가 왔어요. ES2026 기대됩니다.",
    createdAt: "2026-02-23T12:00:00Z",
  },
  {
    id: 35,
    authorId: 105,
    authorName: "reactHan",
    avatarUrl: "https://avatars.githubusercontent.com/u/5?v=4",
    content: "React 19 써보고 있는데, 서버 컴포넌트 정말 좋네요.",
    createdAt: "2026-02-23T10:30:00Z",
  },
  {
    id: 36,
    authorId: 131,
    authorName: "zigLee",
    avatarUrl: "https://avatars.githubusercontent.com/u/31?v=4",
    content: "Zig 언어 공부 시작했어요. 시스템 프로그래밍 재밌네요!",
    createdAt: "2026-02-13T09:00:00Z",
  },
  {
    id: 37,
    authorId: 132,
    authorName: "elixirPark",
    avatarUrl: "https://avatars.githubusercontent.com/u/32?v=4",
    content: "함수형 프로그래밍의 매력에 빠졌습니다. Elixir 최고!",
    createdAt: "2026-02-06T14:00:00Z",
  },
  {
    id: 38,
    authorId: 133,
    authorName: "scalaChoi",
    avatarUrl: "https://avatars.githubusercontent.com/u/33?v=4",
    content: "새해 목표로 매일 코딩 1시간! 벌써 한 달 넘게 달리는 중.",
    createdAt: "2026-01-15T11:30:00Z",
  },
  {
    id: 39,
    authorId: 134,
    authorName: "haskellKim",
    avatarUrl: "https://avatars.githubusercontent.com/u/34?v=4",
    content: "모나드 드디어 이해했어요... 감동의 눈물 😭",
    createdAt: "2025-12-25T18:00:00Z",
  },
  {
    id: 40,
    authorId: 135,
    authorName: "cSharpJung",
    avatarUrl: "https://avatars.githubusercontent.com/u/35?v=4",
    content: "Unity로 게임 만들다가 발견한 서비스! 코딩 집중할 때 좋아요.",
    createdAt: "2025-11-10T10:00:00Z",
  },
  {
    id: 41,
    authorId: 136,
    authorName: "luaYoon",
    avatarUrl: "https://avatars.githubusercontent.com/u/36?v=4",
    content: "Neovim 설정 삽질하다가 하루가 다 갔네요 ㅋㅋ",
    createdAt: "2025-08-20T15:30:00Z",
  },
  {
    id: 42,
    authorId: 137,
    authorName: "perlShin",
    avatarUrl: "https://avatars.githubusercontent.com/u/37?v=4",
    content:
      "오래전에 가입했는데 아직도 잘 쓰고 있어요. 좋은 서비스 감사합니다!",
    createdAt: "2025-02-14T09:00:00Z",
  },
];
