name: Backend CD

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install and Build Backend
        working-directory: ./backend
        run: |
          pnpm install
          pnpm run build

      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          pnpm install
          NODE_ENV=production NEXT_PUBLIC_API_URL=https://commitplease.com NEXT_PUBLIC_SOCKET_URL=https://commitplease.com pnpm run build

      - name: Copy build artifacts to Dev Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_KEY }}
          port: 22
          # backend/dist, backend/public, package.json 등을 전송합니다.
          source: 'backend/dist/*,backend/public/*,backend/package.json,backend/pnpm-lock.yaml,ecosystem.config.js,package.json'
          target: '/home/${{ secrets.ORACLE_USERNAME }}/web19-estrogenquattro/'
          strip_components: 0

  restart_service:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Restart Service via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          port: 22
          script: |
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm use 24.13.1
            export PNPM_HOME="$HOME/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"

            cd web19-estrogenquattro/backend
            pnpm install --prod

            cd ..
            pnpm run deploy:prod
